stages:
  - build_image
  - test
  - build

build_image:
  stage: build_image
  image: docker
  services:
    - docker:dind
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - echo $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE

test:
  image: $CI_REGISTRY_IMAGE
  stage: test
  script:
    - cmake --preset linux-dev
    - make build/linux-dev/tests/
    - ./build/linux-dev/tests/tests
  artifacts:
    paths:
      - "build/"

build:
  stage: build
  script:
    - make build/linux-dev/src/
  artifacts:
    paths:
      - "build/"