stages:
  - build_image
  - test
  - build

build_image:
  stage: build_image
  image: debian:latest
  script:
    - apt update
    - apt install -y curl
    - apt install -y zip
    - apt install -y git
    - apt install -y make
    - apt install -y cmake
    - git clone https://github.com/microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh
    - export VCPKG_ROOT=$(pwd)
    - export PATH=$VCPKG_ROOT:/bin

test:
  stage: test
  script:
    - echo "test"

build:
  stage: build
  script:
    - echo "build"