stages:
  - build_image
  - test
  - build

build_image:
  stage: build_image
  image: debian:latest
  script:
    - apt update
    - apt install -y curl
    - apt install -y zip
    - apt install -y git
    - apt install -y make
    - apt install -y cmake
    - git clone https://github.com/microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh
    - export VCPKG_ROOT=$(pwd)
    - export PATH=$VCPKG_ROOT:/bin

test:
  stage: test
  script:
    - cmake --preset linux-dev
    - make build/linux-dev/tests/
    - ./build/linux-dev/tests/tests
  artifacts:
    paths:
      - "build/"

build:
  stage: build
  script:
    - make build/linux-dev/src/
  artifacts:
    paths:
      - "build/"